// ===================================================
// === WARNING! DO NOT EDIT THIS FILE! ===============
// === This code was generated by EasyC (Prototype) ==
// === and transpiled from an input file =============
// ===================================================

#include <stdio.h>
#include <stdlib.h>
#include "example/easyc/file.h"
#include "normal/c/file.h"

#ifndef EC__NULL__CHECK
#include <stdio.h>
#include <stdlib.h>
#define EC__NULL__CHECK(x) \
do { \
    if ((x) == NULL) { \
        fprintf(stderr, "File %s - Line %d had illegal null pointer, now exiting...\n", __FILE__, __LINE__); \
        exit(1); \
    } \
} while(0)
#endif

// ========= prefix =========

static int add(const int a, const int b)
{
    return a + b;
}

int int_math__add(const int addend_a, const int addend_b)
{
    return add(addend_a, addend_b);
}

int int_math__subtract(const int minuend, const int subtrahend)
{
    return int_math__add(minuend, -subtrahend);
}

static int int_math__detail__divide_and_round(const int numerator, const int denominator)
{
    if ((numerator > 0 && denominator > 0) || (numerator < 0 && denominator < 0))
    {
        return (numerator + denominator / 2) / denominator;
    }
    else
    {
        return (numerator - denominator / 2) / denominator;
    }
}

static void int_math__detail__abort_for_illegal_denominator(const int denominator)
{
    if (denominator == 0)
    {
        printf("Error: division by zero.");
        exit(1);
    }
}

int int_math__divide(const int numerator, const int denominator)
{
    int_math__detail__abort_for_illegal_denominator(denominator);
    return int_math__detail__divide_and_round(numerator, denominator);
}

int int_math__multiply(const int factor_a, const int factor_b)
{
    return factor_a*factor_b;
}

// ========= mut =========

int normalize_to_range(const int value, const int low_boundary, const int high_boundary)
{
    int result = value;

    if (result < low_boundary)
    {
        result = low_boundary;
    }
    if (result > high_boundary)
    {
        result = high_boundary;
    }

    return result;
}

void set_to_zero_if_negative(int* const i_ptr)
{
    if (i_ptr != NULL && (*i_ptr) < 0)
    {
        (*i_ptr) = 0;
    }
}

// ========= safe =========

float dereference_float(const float* const f_ptr)
{
    EC__NULL__CHECK(f_ptr);
    return(*f_ptr);
}

static float ratio = 0.4;

const float* const get_ratio()
{
    const float* const result = ratio;
    EC__NULL__CHECK(result);
    return result;
}

// ========= typestruct =========

struct Color
{
    int r;
    int g;
    int b;
};
typedef struct Color Color;

// ========= indef =========

#define Color__set__white__MAX ((const int)(255))
#define Color__set__white__WHITE ((const Color){ .r = Color__set__white__MAX, .g = Color__set__white__MAX, .b = Color__set__white__MAX })
void Color__set__white(Color* const col)
{
    EC__NULL__CHECK(col);
    (*col) = Color__set__white__WHITE;
}

// ========= typenum =========

struct LogOption { int LogOption_value; };
typedef struct LogOption LogOption;
#define LogOption__info ((const LogOption){ .LogOption_value = 0 })
#define LogOption__warning ((const LogOption){ .LogOption_value = 1 })
#define LogOption__error ((const LogOption){ .LogOption_value = 2 })
#define LogOption__count 3
#define LogOption__equals(a, b) ((a).LogOption_value == (b).LogOption_value)
#define LogOption__get(a) ((a).LogOption_value)

void Log(const char* const log, const LogOption logopt)
{
    if (LogOption__equals(logopt, LogOption__info))
    {
        LogInfo(log);
    }
    else if (LogOption__equals(logopt, LogOption__warning))
    {
        LogWarning(log);
    }
    else if (LogOption__equals(logopt, LogOption__error))
    {
        LogError(log);
    }
}

// ========= cleanpop =========

struct String
{
    char* data;
    unsigned int size;
    unsigned int capacity;
};
typedef struct String String;
void String__populate(String* const str)
{
    EC__NULL__CHECK(str);
    str->data = NULL;
    str->size = 0;
    str->capacity = 0;
}
void String__cleanup(String* const str)
{
    EC__NULL__CHECK(str);
    free(str->data);
    str->data = NULL;
    str->size = 0;
    str->capacity = 0;
}
void String__set(String* const target, const char* const c_string);
void String__add(String* const target, const char* const addition);
void String__equals(const String* const str1, const String* const str2);

void foo()
{
    String str;
    String__populate(&str);
    String__set(&str, "Hello there!");
    printf("The greeting: %s\n", str->data);
    String__cleanup(&str);
}

void bar()
{
    String greeting_1;
    String__populate(&greeting_1);
    String__set(&greeting_1, "Hello there!");
    const String greeting_2;
    String__populate((String*)&greeting_2);

    if (String__equals(&greeting_1, &greeting_2))
    {
        String doppelganger;
        String__populate(&doppelganger);
        String__set(&doppelganger, "Wow, they are doppelgangers!");
        printf("%s\n", doppelganger->data);
        String__cleanup(&doppelganger);
        String__cleanup((String*)&greeting_2);
        String__cleanup(&greeting_1);
        return;
    }

    if (greeting_1->data == NULL || greeting_1->data == NULL)
    {
        printf("Something went wrong");
        String__cleanup((String*)&greeting_2);
        String__cleanup(&greeting_1);
        return;
    }

    printf("Greeting 1: %s\n", greeting_1->data);
    printf("Greeting 2: %s\n", greeting_2->data);

    String__cleanup((String*)&greeting_2);
    String__cleanup(&greeting_1);
}