// =====================================================
// === WARNING! DO NOT EDIT THIS FILE! =================
// === This code was generated by AlloyC (Prototype) ===
// === and transpiled from an input file ===============
// =====================================================

#include <stdio.h>
#include <stdlib.h>
#include "example/easyc/file..h"
#include "normal/c/file.h"

#ifndef ALC__NULL__CHECK
#include <stdio.h>
#include <stdlib.h>
#define ALC__NULL__CHECK(x) \
do { \
    if ((x) == NULL) { \
        fprintf(stderr, "File %s - Line %d had illegal null pointer, now exiting...\n", __FILE__, __LINE__); \
        exit(1); \
    } \
} while(0)
#endif

// ========= prefix =========

static int add(const int a, const int b)
{
    return a + b;
}

int int_math__add(const int addend_a, const int addend_b)
{
    return add(addend_a, addend_b);
}

int int_math__subtract(const int minuend, const int subtrahend)
{
    return int_math__add(minuend, -subtrahend);
}

static int int_math__detail__divide_and_round(const int numerator, const int denominator)
{
    unsigned const int sign_diff = ((unsigned const int)(numerator ^ denominator)) >> 31;
    const int sign = 1 - 2*sign_diff; // +1 or -1

    const int abs_den = denominator < 0 ? -denominator : denominator;
    const int bias = abs_den / 2;

    return (numerator + sign*bias) / denominator;
}

static void int_math__detail__abort_for_illegal_denominator(const int denominator)
{
    if (denominator == 0)
    {
        printf("Error: division by zero.\n");
        exit(1);
    }
}

int int_math__divide(const int numerator, const int denominator)
{
    int_math__detail__abort_for_illegal_denominator(denominator);
    return int_math__detail__divide_and_round(numerator, denominator);
}

int int_math__multiply(const int factor_a, const int factor_b)
{
    return factor_a*factor_b;
}

// ========= mut =========

int normalize_to_range(const int value, const int low_boundary, const int high_boundary)
{
    int result = value;

    if (result < low_boundary)
    {
        result = low_boundary;
    }
    if (result > high_boundary)
    {
        result = high_boundary;
    }

    return result;
}

void set_to_zero_if_negative(int* const i_ptr)
{
    if (i_ptr != NULL && (*i_ptr) < 0)
    {
        (*i_ptr) = 0;
    }
}

// ========= check =========

float dereference_float(const float* const f_ptr)
{
    ALC__NULL__CHECK(f_ptr);
    return(*f_ptr);
}

static float ratio = 0.4;

const float* const get_ratio()
{
    const float* const result = &ratio;
    ALC__NULL__CHECK(result);
    return result;
}

// ========= typestruct =========

struct Color
{
    int r;
    int g;
    int b;
};
typedef struct Color Color;

// ========= indef =========

#define Color__set__white__MAX ((const int)(255))
#define Color__set__white__WHITE ((const Color){ .r = Color__set__white__MAX, .g = Color__set__white__MAX, .b = Color__set__white__MAX })
void Color__set__white(Color* const col)
{
    ALC__NULL__CHECK(col);
    (*col) = Color__set__white__WHITE;
}

// ========= typenum =========

struct LogOption { int LogOption_value; };
typedef struct LogOption LogOption;
#define LogOption__info ((const LogOption){ .LogOption_value = 0 })
#define LogOption__warning ((const LogOption){ .LogOption_value = 1 })
#define LogOption__error ((const LogOption){ .LogOption_value = 2 })
#define LogOption__count 3
#define LogOption__equals(a, b) ((a).LogOption_value == (b).LogOption_value)
#define LogOption__get(a) ((a).LogOption_value)

void Log(const char* const log, const LogOption logopt)
{
    if (LogOption__equals(logopt, LogOption__info))
    {
        LogInfo(log);
    }
    else if (LogOption__equals(logopt, LogOption__warning))
    {
        LogWarning(log);
    }
    else if (LogOption__equals(logopt, LogOption__error))
    {
        LogError(log);
    }
}

// ========= typenum with own internal type =========

struct GraphicMode { char GraphicMode_value; };
typedef struct GraphicMode GraphicMode;
#define GraphicMode__performance ((const GraphicMode){ .GraphicMode_value = 'p' })
#define GraphicMode__quality ((const GraphicMode){ .GraphicMode_value = 'q' })
#define GraphicMode__count 2
#define GraphicMode__equals(a, b) ((a).GraphicMode_value == (b).GraphicMode_value)
#define GraphicMode__get(a) ((a).GraphicMode_value)

// ========= typenum based on c-strings =========

struct ErrorType { const char* ErrorType_value; };
typedef struct ErrorType ErrorType;
#define ErrorType__mechanical ((const ErrorType){ .ErrorType_value = "Mechanical failure" })
#define ErrorType__electrical ((const ErrorType){ .ErrorType_value = "Electrical failure" })
#define ErrorType__software ((const ErrorType){ .ErrorType_value = "Software failure" })
#define ErrorType__count 3
#define ErrorType__equals(a, b) ((a).ErrorType_value == (b).ErrorType_value)
#define ErrorType__get(a) ((a).ErrorType_value)

void PrintErrorMessage(const ErrorType err)
{
    const char* const err_msg = ErrorType__get(err);
    printf("%s\n", err_msg);
}

// ========= cleanpop =========

struct String
{
    char* data;
    unsigned int size;
    unsigned int capacity;
};
typedef struct String String;
void String__populate(String* const str)
{
    ALC__NULL__CHECK(str);
    str->data = NULL;
    str->size = 0;
    str->capacity = 0;
}
void String__cleanup(String* const str)
{
    ALC__NULL__CHECK(str);
    free(str->data);
    str->data = NULL;
    str->size = 0;
    str->capacity = 0;
}
void String__set(String* const target, const char* const c_string);
void String__add(String* const target, const char* const addition);
int String__equals(const String* const str1, const String* const str2);

void foo()
{
    String str;
    String__populate(&str);
    String__set(&str, "Hello there!");
    const String* const str_view = &str;
    printf("The greeting: %s\n", str_view->data);
    String__cleanup(&str);
}

void bar()
{
    String greeting_1;
    String__populate(&greeting_1);
    String__set(&greeting_1, "Hello there!");
    const String* const greeting_1_view = &greeting_1;

    String greeting_2;
    String__populate(&greeting_2);
    const String* const greeting_2_view = &greeting_2;

    if (String__equals(greeting_1_view, greeting_2_view))
    {
        String doppelganger;
        String__populate(&doppelganger);
        String__set(&doppelganger, "Wow, they are doppelgangers!");
        printf("%s\n", (&doppelganger)->data);
        String__cleanup(&doppelganger);
        String__cleanup(&greeting_2);
        String__cleanup(&greeting_1);
        return;
    }

    if (greeting_1_view->data == NULL || greeting_2_view->data == NULL)
    {
        printf("Something went wrong");
        String__cleanup(&greeting_2);
        String__cleanup(&greeting_1);
        return;
    }

    printf("Greeting 1: %s\n", greeting_1_view->data);
    printf("Greeting 2: %s\n", greeting_2_view->data);

    String__cleanup(&greeting_2);
    String__cleanup(&greeting_1);
}

// ========= cleanpop with arguments =========

void String__populate_with_1(String* const str, const char* const c_string)
{
    ALC__NULL__CHECK(str);
    ALC__NULL__CHECK(c_string);
    String__populate(str);
    String__set(str, c_string);
}

void baz()
{
    String str;
    String__populate_with_1(&str, "Initial string!");
    printf("Data: %s\n", (&str)->data);
    String__cleanup(&str);
}

void String__populate_with_2(String* const str, const char c, const int repeat_char_count);
int some_number();

void foofoo()
{
    String str;
    String__populate_with_2(&str, 'A', some_number());
    if ((&str)->size > 5) {
        String__cleanup(&str);
        return;
    }

    // do stuff
    String__cleanup(&str);
}

// ========= cleanpop with move semantics =========

String__move(String* const from, String* const to)
{
    ALC__NULL__CHECK(from);
    ALC__NULL__CHECK(to);
    if (to == from)
    {
        return;
    }

    String__cleanup(to);
    *to = *from;
    from->data = NULL;
    from->size = 0;
    from->capacity = 0;
}

void foobar()
{
    String str_1;
    String__populate_with_1(&str_1, "Start value");
    // do stuff
    String str_2;
    String__populate(&str_2);
    String__move(&str_1, &str_2);
    // do more stuff
    String__cleanup(&str_2);
    String__cleanup(&str_1);
}

// ========= cleanpop macros and standard types =========

#define int__populate(i) (*i) = 0
#define int__cleanup(i)

void foobaz()
{
    int i;
    int__populate(&i);
    // Do stuff
    int__cleanup(&i);
}